"""Apply audit-CONFIRMED title files (dist/titles/<source>.json) into catalog.db and
emit a D1 title-delta, then rebuild the local FTS.

Title files are {series_id: title} of OFFICIAL source labels (composed in the
adversarial enrich->audit workflow). This script:
  1. updates `series.title` for every id in each named file that EXISTS in the catalog
     (ids not in the catalog are skipped, loudly counted),
  2. rebuilds the local `series_fts` so keyword search reflects the new titles,
  3. writes dist/d1/titles/part_*.sql -- UPDATE-only delta for the LIVE D1 (no
     txn/pragma, small chunks), idempotent and safe to replay.

Usage:
    python core/apply_title_wave.py imf_pctot imf_fdi ...      # explicit list
The caller passes ONLY audit-confirmed sources. sipri's known-bad file is refused.
"""
from __future__ import annotations

import json
import os
import sqlite3
import sys

_THIS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(_THIS, ".."))
CATALOG = os.path.join(ROOT, "data", "catalog.db")
TITLES_DIR = os.path.join(ROOT, "dist", "titles")
OUT_DIR = os.path.join(ROOT, "dist", "d1", "titles")

MAX_BYTES = 10_000_000
MAX_STMTS = 1500
_REFUSE = set()  # (was {"sipri"} — its file is now corrected: units=US$ millions, base year (2024) verified against the SIPRI ingest-log sheet name)


def _lit(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def load_titles(sources: list[str]) -> dict[str, str]:
    merged: dict[str, str] = {}
    for s in sources:
        if s in _REFUSE:
            print(f"  REFUSED {s} (known-bad title file)")
            continue
        p = os.path.join(TITLES_DIR, f"{s}.json")
        if not os.path.exists(p):
            print(f"  MISSING {s}.json -- skipped")
            continue
        d = json.load(open(p, encoding="utf-8"))
        if not isinstance(d, dict) or not d:
            print(f"  EMPTY {s}.json -- skipped")
            continue
        merged.update(d)
        print(f"  loaded {s}: {len(d):,} titles")
    return merged


def apply_local(titles: dict[str, str]) -> list[tuple[str, str]]:
    """UPDATE catalog.db; return the (series_id,title) pairs that actually landed."""
    conn = sqlite3.connect(CATALOG)
    landed: list[tuple[str, str]] = []
    try:
        have = {r[0] for r in conn.execute("SELECT series_id FROM series")}
        miss = 0
        for sid, title in titles.items():
            if sid not in have:
                miss += 1
                continue
            conn.execute("UPDATE series SET title=? WHERE series_id=?", (title, sid))
            landed.append((sid, title))
        conn.commit()
        print(f"applied {len(landed):,} titles to catalog.db ({miss:,} ids not in catalog, skipped)")
        # rebuild local FTS so search reflects new titles
        has_fts = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE name='series_fts'").fetchone()
        if has_fts:
            conn.execute("DELETE FROM series_fts")
            conn.execute("INSERT INTO series_fts(series_id,title,geography) "
                         "SELECT series_id,title,geography FROM series")
            conn.commit()
            n = conn.execute("SELECT COUNT(*) FROM series_fts").fetchone()[0]
            print(f"rebuilt local series_fts: {n:,} rows")
    finally:
        conn.close()
    return landed


def emit_delta(landed: list[tuple[str, str]]) -> list[str]:
    os.makedirs(OUT_DIR, exist_ok=True)
    for f in os.listdir(OUT_DIR):
        if f.startswith("part_") and f.endswith(".sql"):
            os.remove(os.path.join(OUT_DIR, f))
    files: list[str] = []
    part, buf, bb = 0, [], 0
    header = ("-- Econ Data Library title delta for Cloudflare D1 (UPDATE-only; no txn/pragma).\n"
              "-- Generated by core/apply_title_wave.py.\n")

    def flush():
        nonlocal part, buf, bb
        if not buf:
            return
        p = os.path.join(OUT_DIR, f"part_{part:03d}.sql")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(header + "\n".join(buf) + "\n")
        files.append(p)
        part, buf, bb = part + 1, [], 0

    for sid, title in landed:
        stmt = f"UPDATE series SET title={_lit(title)} WHERE series_id={_lit(sid)};"
        sb = len(stmt.encode("utf-8")) + 1
        if buf and (bb + sb > MAX_BYTES or len(buf) >= MAX_STMTS):
            flush()
        buf.append(stmt)
        bb += sb
    flush()
    print(f"wrote {len(files)} D1 title-delta file(s) to {OUT_DIR} ({len(landed):,} UPDATEs)")
    return files


def main(argv: list[str]) -> None:
    if not argv:
        print("usage: python core/apply_title_wave.py <source> [<source> ...]")
        raise SystemExit(2)
    print("== loading title files ==")
    titles = load_titles(argv)
    if not titles:
        print("nothing to apply")
        return
    print("== applying to catalog.db ==")
    landed = apply_local(titles)
    print("== emitting D1 delta ==")
    emit_delta(landed)
    print("DONE. Next: push dist/d1/titles/part_*.sql to D1, then rebuild D1 series_fts.")


if __name__ == "__main__":
    main(sys.argv[1:])
