"""Emit a D1 delta that pushes localized titles (and the full enriched metadata
that carries them) for every series whose local catalog.db metadata now holds a
`titles` object.

Why a DELTA, not a re-import: the live D1 already has the catalog (595k+ series).
Re-importing the whole series table would ship hundreds of MB; we only need to
refresh the `metadata` column for the ~33k series that gained official
translations. Each row becomes one `UPDATE series SET metadata=? WHERE
series_id=?`. UPDATEs for ids not present in D1 are harmless no-ops, so the delta
is safe to apply against any slice.

D1 RULES (learned, see project_cloudflare_deploy): NO `BEGIN/COMMIT/PRAGMA`
(D1 wraps its own txn); keep each file well under the remote-execute size cap.
We chunk to <= MAX_BYTES per file AND <= MAX_STMTS statements, then VERIFY every
file by replaying it into a throwaway in-memory SQLite so a broken escape never
reaches the wire.

    python core/export_d1_i18n_delta.py
    cd api/worker && for f in ../../dist/d1/i18n/part_*.sql; do \
        ./node_modules/.bin/wrangler d1 execute econ-catalog --remote --file "$f"; done
"""
from __future__ import annotations

import json
import os
import sqlite3

_THIS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(_THIS, ".."))
CATALOG = os.path.join(ROOT, "data", "catalog.db")
OUT_DIR = os.path.join(ROOT, "dist", "d1", "i18n")

MAX_BYTES = 10_000_000   # ~10 MB/file (well under the remote-execute cap)
MAX_STMTS = 1500         # belt-and-suspenders statement cap per file


def _lit(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def _iter_translated(conn: sqlite3.Connection):
    """(series_id, metadata_text) for every series carrying a titles object.
    We re-serialize the parsed JSON canonically so the wire value is exactly what
    the API will parse back -- and we ASSERT a non-empty titles object so a stray
    match on the substring '%titles%' can never ship a row without translations."""
    cur = conn.execute(
        "SELECT series_id, metadata FROM series "
        "WHERE metadata LIKE '%titles%' ORDER BY series_id")
    for sid, md in cur:
        if not md:
            continue
        obj = json.loads(md)
        titles = obj.get("titles")
        if not isinstance(titles, dict) or not titles:
            continue  # substring matched but no real titles -> skip
        # canonical compact JSON, non-ASCII preserved (Arabic/Chinese stay UTF-8)
        text = json.dumps(obj, ensure_ascii=False, separators=(",", ":"))
        yield sid, text


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    # clear any prior parts so a re-run never leaves stale files behind
    for f in os.listdir(OUT_DIR):
        if f.startswith("part_") and f.endswith(".sql"):
            os.remove(os.path.join(OUT_DIR, f))

    conn = sqlite3.connect(CATALOG)
    rows = list(_iter_translated(conn))
    conn.close()

    files: list[tuple[str, int]] = []
    part = 0
    buf: list[str] = []
    buf_bytes = 0
    header = ("-- Econ Data Library i18n delta (localized titles) for Cloudflare D1.\n"
              "-- Generated by core/export_d1_i18n_delta.py. UPDATE-only; no txn/pragma.\n")

    def flush():
        nonlocal part, buf, buf_bytes
        if not buf:
            return
        path = os.path.join(OUT_DIR, f"part_{part:03d}.sql")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(header)
            fh.write("\n".join(buf) + "\n")
        files.append((path, len(buf)))
        part += 1
        buf = []
        buf_bytes = 0

    for sid, text in rows:
        stmt = f"UPDATE series SET metadata={_lit(text)} WHERE series_id={_lit(sid)};"
        sb = len(stmt.encode("utf-8")) + 1
        if buf and (buf_bytes + sb > MAX_BYTES or len(buf) >= MAX_STMTS):
            flush()
        buf.append(stmt)
        buf_bytes += sb
    flush()

    total = sum(n for _, n in files)
    print(f"rows with real titles: {total:,}  ->  {len(files)} file(s) in {OUT_DIR}")
    for path, n in files:
        mb = os.path.getsize(path) / 1e6
        print(f"  {os.path.basename(path)}  {n:>6,} stmts  {mb:5.1f} MB")

    # ---- VERIFY: replay every file into a throwaway SQLite (== D1 parser) ----
    mem = sqlite3.connect(":memory:")
    mem.execute("CREATE TABLE series (series_id TEXT PRIMARY KEY, metadata TEXT)")
    # seed one known id so at least one UPDATE actually lands and round-trips
    probe = rows[0][0] if rows else None
    if probe:
        mem.execute("INSERT INTO series(series_id, metadata) VALUES (?, '{}')", (probe,))
    applied = 0
    for path, _ in files:
        with open(path, encoding="utf-8") as fh:
            sql = fh.read()
        mem.executescript(sql)
        applied += 1
    if probe:
        got = mem.execute(
            "SELECT metadata FROM series WHERE series_id=?", (probe,)).fetchone()[0]
        obj = json.loads(got)
        ok = isinstance(obj.get("titles"), dict) and bool(obj["titles"])
        print(f"  verify replay {applied} file(s); probe {probe!r} titles-langs="
              f"{sorted(obj.get('titles', {}))}  {'PASS' if ok else 'FAIL'}")
    mem.close()


if __name__ == "__main__":
    main()
