"""Export the local catalog + freshness state to a D1-ready SQL file.

D1 IS SQLite, so the Worker's queries (catalog/license/series, FTS5 search,
unit_state/source_state for /v1/last-updates) run unchanged once this SQL is loaded:

    wrangler d1 create econ-catalog
    wrangler d1 execute econ-catalog --remote --file=dist/d1/econ_catalog.sql

This script reads data/catalog.db (license, source, series + the series_fts FTS5
table) and data/_aqueduct/state.db (unit_state, source_state) and emits ONE portable
.sql with CREATE TABLE + batched INSERTs. It then VERIFIES the emitted SQL by loading
it into a fresh in-memory SQLite and asserting row counts match — so a cutover never
ships a broken dump. No Cloudflare credentials needed to produce or verify this file.
"""
from __future__ import annotations

import os
import sqlite3

_THIS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(_THIS, ".."))
CATALOG = os.path.join(ROOT, "data", "catalog.db")
STATE = os.path.join(ROOT, "data", "_aqueduct", "state.db")
OUT_DIR = os.path.join(ROOT, "dist", "d1")
OUT = os.path.join(OUT_DIR, "econ_catalog.sql")

# Tables to export from each db. Order matters (FTS rebuilt last).
_CATALOG_TABLES = ["license", "source", "series"]
_STATE_TABLES = ["unit_state", "source_state"]
_BATCH = 20  # rows per multi-VALUES INSERT (D1 caps statement length ~ SQLITE_TOOBIG)


def _sql_lit(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def _create_sql(conn: sqlite3.Connection, table: str) -> str | None:
    row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    return row[0] if row and row[0] else None


def _dump_table(conn: sqlite3.Connection, table: str, lines: list[str]) -> int:
    create = _create_sql(conn, table)
    if not create:
        return 0
    cols = [r[1] for r in conn.execute(f"PRAGMA table_info({table})")]
    collist = ", ".join(f'"{c}"' for c in cols)
    lines.append(f"DROP TABLE IF EXISTS {table};")
    lines.append(create.rstrip(";") + ";")
    rows = conn.execute(f"SELECT {collist} FROM {table}").fetchall()
    for i in range(0, len(rows), _BATCH):
        chunk = rows[i:i + _BATCH]
        values = ",\n".join("(" + ", ".join(_sql_lit(v) for v in r) + ")" for r in chunk)
        lines.append(f"INSERT INTO {table} ({collist}) VALUES\n{values};")
    return len(rows)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    counts: dict[str, int] = {}
    # NB: NO 'BEGIN TRANSACTION'/'COMMIT'/'PRAGMA' — D1 rejects raw transaction
    # statements (it wraps imports in its own transaction) and ignores PRAGMA.
    lines = [
        "-- Econ Data Library catalog + freshness state, exported for Cloudflare D1.",
        "-- Generated by core/export_d1.py. D1 is SQLite; load with:",
        "--   wrangler d1 execute <db> --remote --file=dist/d1/econ_catalog.sql",
    ]

    cat = sqlite3.connect(CATALOG)
    try:
        for t in _CATALOG_TABLES:
            counts[t] = _dump_table(cat, t, lines)
        # FTS5 search table: recreate + repopulate from series (matches core/catalog.py).
        has_fts = cat.execute(
            "SELECT 1 FROM sqlite_master WHERE name='series_fts'").fetchone()
        if has_fts:
            lines.append("DROP TABLE IF EXISTS series_fts;")
            lines.append("CREATE VIRTUAL TABLE series_fts USING fts5"
                         "(series_id UNINDEXED, title, geography);")
            lines.append("INSERT INTO series_fts(series_id,title,geography) "
                         "SELECT series_id,title,geography FROM series;")
            counts["series_fts"] = counts.get("series", 0)
    finally:
        cat.close()

    if os.path.exists(STATE):
        st = sqlite3.connect(STATE)
        try:
            for t in _STATE_TABLES:
                counts[t] = _dump_table(st, t, lines)
        finally:
            st.close()

    sql = "\n".join(lines) + "\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(sql)

    size_mb = os.path.getsize(OUT) / 1e6
    print(f"wrote {OUT}  ({size_mb:.1f} MB)")
    for t, n in counts.items():
        print(f"  {t:14} {n:>8,} rows")

    # ---- VERIFY: replay the emitted dump into a fresh FILE-BACKED SQLite (== D1) ----
    # A single executescript() on the full ~1 GB dump exceeds SQLite's
    # SQLITE_MAX_SQL_LENGTH ("query string is too large"). Each `line` is already one
    # complete statement, so replay them in blocks that stay well under the limit.
    verify_db = OUT + ".verify.sqlite"
    if os.path.exists(verify_db):
        os.remove(verify_db)
    mem = sqlite3.connect(verify_db)
    try:
        _VCHUNK = 2000  # statements per executescript block
        for i in range(0, len(lines), _VCHUNK):
            mem.executescript("\n".join(lines[i:i + _VCHUNK]))
        mem.commit()
        ok = True
        for t in _CATALOG_TABLES + _STATE_TABLES:
            if t not in counts:
                continue
            got = mem.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
            flag = "OK" if got == counts[t] else "MISMATCH"
            if got != counts[t]:
                ok = False
            print(f"  verify {t:14} {got:>8,}  {flag}")
        # FTS query must work (proves search is live on D1).
        fts_n = mem.execute(
            "SELECT COUNT(*) FROM series_fts WHERE series_fts MATCH 'gdp'").fetchone()[0]
        print(f"  verify series_fts MATCH 'gdp' -> {fts_n} hits")
        print("VERIFY:", "PASS" if ok else "FAIL")
    finally:
        mem.close()
        try:
            os.remove(verify_db)
        except OSError:
            pass


if __name__ == "__main__":
    main()
