"""Emit a D1 delta that INSERTs newly-titled series into the live search index.

The live D1 (`econ-catalog`) is the CLEAN TITLED search index, NOT the full 1.27M
catalog. When a previously raw-key source gets official titles (adversarial title
wave), its series must be INSERTED into D1 (they weren't there before) — an UPDATE
would be a no-op. This reads the FULL series rows for the given (now-titled) sources
from catalog.db and emits:

  * dist/d1/newseries/part_*.sql  -- INSERT OR REPLACE INTO series (...) VALUES (...)
                                     in small batches (~20 rows; D1 statement cap),
                                     ONLY for series that carry a real (non-raw) title.
  * dist/d1/newseries/_fts_rebuild.sql -- DELETE+INSERT...SELECT to rebuild series_fts
                                     from the (now larger) series table. Run LAST.

D1 rules: NO BEGIN/COMMIT/PRAGMA; small chunks. Idempotent (INSERT OR REPLACE +
deterministic FTS rebuild). Verified by replay into in-memory SQLite.

Usage:
    python core/export_d1_new_series.py imf_pctot imf_fdi ...   # confirmed sources
"""
from __future__ import annotations

import json
import os
import sqlite3
import sys

_THIS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(_THIS, ".."))
CATALOG = os.path.join(ROOT, "data", "catalog.db")
TITLES_DIR = os.path.join(ROOT, "dist", "titles")
OUT_DIR = os.path.join(ROOT, "dist", "d1", "newseries")

COLS = ["series_id", "source_id", "title", "frequency", "unit", "geography",
        "category", "license_id", "start_date", "end_date", "last_updated", "metadata"]
ROWS_PER_STMT = 20
MAX_BYTES = 8_000_000
_REFUSE = set()  # (was {"sipri"} — corrected: US$ millions + verified base year 2024)


def _lit(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def titled_ids(sources: list[str]) -> set[str]:
    ids: set[str] = set()
    for s in sources:
        if s in _REFUSE:
            print(f"  REFUSED {s}")
            continue
        p = os.path.join(TITLES_DIR, f"{s}.json")
        if not os.path.exists(p):
            print(f"  MISSING {s}.json")
            continue
        d = json.load(open(p, encoding="utf-8"))
        if isinstance(d, dict):
            ids.update(d.keys())
    return ids


def main(argv: list[str]) -> None:
    if not argv:
        print("usage: python core/export_d1_new_series.py <source> [...]")
        raise SystemExit(2)
    os.makedirs(OUT_DIR, exist_ok=True)
    for f in os.listdir(OUT_DIR):
        if f.endswith(".sql"):
            os.remove(os.path.join(OUT_DIR, f))

    want = titled_ids(argv)
    print(f"titled ids requested: {len(want):,}")
    conn = sqlite3.connect(CATALOG)
    collist = ", ".join(f'"{c}"' for c in COLS)
    # pull only the rows that exist AND carry a non-raw title (title != stripped id)
    rows = []
    for r in conn.execute(
            f"SELECT {collist} FROM series WHERE source_id IN "
            f"({','.join('?'*len(argv))})", argv):
        sid = r[0]
        if sid in want and r[2] and r[2] != sid and r[2] != sid.split(':', 1)[-1]:
            rows.append(r)
    conn.close()
    print(f"rows to INSERT (titled, existing): {len(rows):,}")

    files: list[str] = []
    part, buf, bb = 0, [], 0
    header = ("-- Econ Data Library new-series delta for D1 (INSERT OR REPLACE; no txn/pragma).\n"
              "-- Generated by core/export_d1_new_series.py.\n")

    def flush():
        nonlocal part, buf, bb
        if not buf:
            return
        p = os.path.join(OUT_DIR, f"part_{part:03d}.sql")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(header + "\n".join(buf) + "\n")
        files.append(p)
        part, buf, bb = part + 1, [], 0

    for i in range(0, len(rows), ROWS_PER_STMT):
        chunk = rows[i:i + ROWS_PER_STMT]
        vals = ",\n".join("(" + ", ".join(_lit(v) for v in row) + ")" for row in chunk)
        stmt = f"INSERT OR REPLACE INTO series ({collist}) VALUES\n{vals};"
        sb = len(stmt.encode("utf-8")) + 1
        if buf and (bb + sb > MAX_BYTES):
            flush()
        buf.append(stmt)
        bb += sb
    flush()

    # INCREMENTAL FTS (run LAST, after the inserts land). We do NOT do a full
    # DELETE+rebuild: past ~1.1M rows that single op exceeds D1's storage-operation
    # timeout and rolls back (FTS silently stays stale). Instead insert ONLY the
    # rows for the sources being added. These sources are NEW to D1, so they have
    # no prior series_fts rows -> a plain INSERT cannot create duplicates. (To
    # RE-apply an already-indexed source, first DELETE its series_fts rows.)
    fts = os.path.join(OUT_DIR, "_fts_rebuild.sql")
    with open(fts, "w", encoding="utf-8") as fh:
        fh.write("-- INCREMENTAL series_fts refresh, per source. Run AFTER part_*.sql.\n")
        fh.write("-- Full DELETE+rebuild times out on D1 past ~1.1M rows. We DELETE-then-INSERT\n")
        fh.write("-- per source (idempotent) because a source may ALREADY be in D1/FTS with raw\n")
        fh.write("-- titles (e.g. ksh) -- a plain INSERT would then DOUBLE its FTS rows.\n")
        for s in argv:
            lit = "'" + s.replace("'", "''") + "'"
            fh.write(f"DELETE FROM series_fts WHERE series_id IN "
                     f"(SELECT series_id FROM series WHERE source_id={lit});\n")
            fh.write(f"INSERT INTO series_fts(series_id,title,geography) "
                     f"SELECT series_id,title,geography FROM series WHERE source_id={lit};\n")

    print(f"wrote {len(files)} INSERT file(s) + _fts_rebuild.sql to {OUT_DIR}")

    # VERIFY: replay inserts into in-memory SQLite
    mem = sqlite3.connect(":memory:")
    mem.execute(f"CREATE TABLE series ({', '.join(c+' TEXT' for c in COLS)}, PRIMARY KEY(series_id))")
    for p in files:
        mem.executescript(open(p, encoding="utf-8").read())
    n = mem.execute("SELECT COUNT(*) FROM series").fetchone()[0]
    mem.close()
    flag = "PASS" if n == len(rows) else f"FAIL ({n} != {len(rows)})"
    print(f"verify replay: {n:,} rows  {flag}")


if __name__ == "__main__":
    main(sys.argv[1:])
